Решения задач sortString,pick,omit
js-tasks-ru/js-20200928_sergey16 pull request #5
Opened 2020-10-03 12:16 UTC by Raikyo777

2020-10-03 12:22 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-04 15:32 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	let newarr = arr.slice();
помните мы говорили про объявления переменных, и отличие использования `let` от `const`?

Замените объявления переменных `let` на `const` в тех переменных которые не будут переприсвоены

2020-10-04 15:33 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	else if (param === 'desc') return newarr.reverse();
в этом решении есть проблема - данные всегда сортируются по `asc` и только после этого происходит проверка `param === 'desc'` и в случае если она положительна, происходит `newarr.reverse()`

Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2020-10-04 15:34 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +	for (let value of fields) if(map.has(value)){newmap.set(value,map.get(value));}
запись в одну строку таких конструкций очень плохо читается.

Вопрос: Для чего в данном коде используется `new Map`? Нужна ли здесь эта структура?

2020-10-04 15:35 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> + 	let map = new Map(Object.entries(obj));
замечания аналогичны решению `pick`

2020-10-04 15:35 UTC, dosandk requested changes
необходимо внести правки согласно комментариям и дать ответы на вопросы

2020-10-04 18:02 UTC, Raikyo777 commented on 02-javascript-data-types/1-sort-strings/index.js
> +	else if (param === 'desc') return newarr.reverse();
Это решение показалось мне более простым , чем извращаться и мутить другой коллатор, тестить его и иметь возможность допустить ошибку , с другими настройками, потому что по сути реверс это и есть перевернутое sort ,и оно будет верным всегда какие бы новые задачки и ухищрения на язык мы не ставили , не понимаю почему это решение неверное? Объяснения как именно перевернуть существенно удлинят код.

2020-10-04 18:22 UTC, Raikyo777 commented on 02-javascript-data-types/1-sort-strings/index.js
> +	let newarr = arr.slice();
Поправил, постарался добавить const везде где не видел переприсвоения

2020-10-04 18:29 UTC, Raikyo777 commented on 02-javascript-data-types/2-pick/index.js
> +	for (let value of fields) if(map.has(value)){newmap.set(value,map.get(value));}
Да нужна, потому что нужно сформировать  2 набора для сравнения и отредактировать новый набор , первый набор ключей можно сделать и сетом, но мне показалось более простым сделать это 2мя мапами, код от этого сложнее не станет, нечитабельнее тоже, мне кажется это вкусовщина, каким способом это делать. я попробовал избавится от объявления мапов но, неизбежно нарывался или на громоздкий код или на ошибки интерпретатора npm, поэтому вернулся к старому варианту.

2020-10-04 18:30 UTC, Raikyo777 commented on 02-javascript-data-types/2-pick/index.js
> +	for (let value of fields) if(map.has(value)){newmap.set(value,map.get(value));}
Конструкцию в новом релизе поправил,сделав более читабельной

2020-10-04 18:30 UTC, Raikyo777 commented on 02-javascript-data-types/3-omit/index.js
> + 	let map = new Map(Object.entries(obj));
Конструкцию в новом релизе поправил,сделав более читабельной

2020-10-06 06:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
- should return existed properties
- should return "undefined" for properties which does not exist
- gets obj.property
- returns undefined for no property
- gets obj.nested.property
- returns undefined for no nested.property
- gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
- should remove an identical consecutive characters that exceed the specified size
- should return empty string if it was passed to function like an argument
- should return empty string if "size" equal 0
- should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should return "undefined" if object wasn't passed
- should swap keys and values and return new object
- should return empty object if was passed object without values
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
- should return array with uniq values
- should return empty array if was passed array without values
- should return empty array if arguments wasn't passed
```

2020-10-06 14:24 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	else if (param === 'desc') return newarr.reverse();
@Raikyo777 после разбора домашек на занятии, появилось ли видение как исправить данный код.
P.S. collator будет всегда один и тот же, в не зависимости от порядка сортировки

2020-10-06 14:25 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +	const map = new Map(Object.entries(obj));
для чего Вы используете `Map` в `pick` и `omit`?
Можем ли мы обойтись без его использования?

2020-10-06 14:26 UTC, dosandk requested changes
посмотрите пожалуйста комменты, внесите изменения.
Если возникнут вопросы - напишите мне в Slack

2020-10-07 11:01 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-07 18:44 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +	return Array.from (set);
подумайте в чем преимущество использования `Array.from` по сравнению с решением через спред синтаксис: `return [...new Set(arr)]`

2020-10-07 18:46 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +				else return undefined;
помните, мы не присваиваем `undefined` так же это утверждение справедливо и для возврата значения. Достаточно просто сделать:
```return```

2020-10-07 18:47 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +			for (const item of path.split('.')){
не следует выполнять `path.split('.')` в цикле, так как данная операция будет происходить на каждой итерации, а по сути это значение нам нужно получить всего один раз - в момент создания геттера

2020-10-07 19:00 UTC, dosandk requested changes
Все решения принимаются, кроме `createGetter` - необходимо внести правки

2020-10-08 09:09 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-08 12:07 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-08 12:21 UTC, Raikyo777 reviewed
> 
> 
> Пожалуйста, не меняйте «системные» файлы.
> Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
> Следующие файлы были изменены:
> 
> ```diff
> - package.json — изменен
> ```

я пытался поставить jest, в описании написано что с его помощью можно проверять одну задачу а не все скопом, он не запускался ни с камими параметрамии я пешил его доустановить и видимо обновились версии , системные файлы я сам не менял...теперь даже не знаю как вернуть все это обратно

2020-10-08 12:21 UTC, Raikyo777 commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +	return Array.from (set);
Мне кажется потому что Array.from предназначен для работы непосредственно с массивами определенной длинны, как в нашем примере ,  а спред это больше работа с "итерируемыми" обьектами .. Тут мы просто конвертируем результат в массив прогнав его через set который не любит одинаковые данные)) и стандартизируется при входе))

2020-10-08 12:21 UTC, Raikyo777 commented on 02-javascript-data-types/2-pick/index.js
> +	const map = new Map(Object.entries(obj));
Ответил в личной беседе. Сопоставление двух мапов мне показалось наиболее простым решением.

2020-10-09 10:52 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-09 20:14 UTC, dosandk commented on package.json
> +    "jest": "^25.5.4",
это изменение нужно откатить, тогда PR может быть смержан. До этого система не даст это сделать. Нельзя изменять системные файлы

2020-10-09 20:14 UTC, dosandk approved these changes
good 👍

2020-10-09 20:14 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-10-10 07:54 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-10 14:31 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-12 08:50 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- package.json — изменен
```

2020-10-12 09:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have ability to be removed
- should have property 'chartHeight
- should render data correctly
- should have ability to be updated by new "data" values (should re-render only body with charts columns)
- should have loading indication if data wasn't passed 
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-10-12 09:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have ability to be removed
- should have property 'chartHeight
- should render data correctly
- should have ability to be updated by new "data" values (should re-render only body with charts columns)
- should have loading indication if data wasn't passed 
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-10-12 12:26 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +		if ('data' in set )this.data = set.data;
на практике оператор `in` не используют для проверки наличия свойств в объекте, так как у него есть один побочный эффект - он проверяет наличие свойство не только в объекте но и в его родительских объектах. В большинстве же случаем, и данная задача не исключение, нас интересуют именно собственный свойства объекта

2020-10-12 12:28 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +	constructor(set){
более гибким подходом, который позволит избежать лишних проверок и условных конструкций ниже, будет использование деструктурирующего присваивания в аргументах функции - об этом поговоим более подробно на занятии.
Пример:

```
  constructor({
    data = [],
    label = '',
    link = '',
    value = 0
  } = {}) {
    this.data = data;
    this.label = label;
    this.link = link;
    this.value = value;
```

2020-10-12 12:28 UTC, dosandk approved these changes

2020-10-12 12:29 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-10-12 19:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
- should be rendered correctly
- should not have default sorting
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
- should sort "asc" correctly for "sortType" equal number
- should sort "desc" correctly for "sortType" equal number
- should have ability to be destroyed
```
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have ability to be removed
- should have property 'chartHeight
- should render data correctly
- should have ability to be updated by new "data" values (should re-render only body with charts columns)
- should have loading indication if data wasn't passed 
```
```diff
NotificationMessage компонент
- should be rendered correctly
- should have ability to set duration
- should be removed after time defined in duration property
- should have ability to set message
- should have ability to set 'success' type of message
- should have ability to set 'error' type of message
- should have ability to define target element for rendering
- should have ability to be destroyed
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-10-13 16:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
- should be rendered correctly
- should not have default sorting
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
- should sort "asc" correctly for "sortType" equal number
- should sort "desc" correctly for "sortType" equal number
- should have ability to be destroyed
```
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
- should render data correctly
- should have ability to be updated by new "data" values (should re-render only body with charts columns)
```
```diff
NotificationMessage компонент
- should be rendered correctly
- should have ability to set duration
- should be removed after time defined in duration property
- should have ability to set message
- should have ability to set 'success' type of message
- should have ability to set 'error' type of message
- should have ability to define target element for rendering
- should have ability to be destroyed
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-10-14 22:20 UTC, dosandk approved these changes
good - решения приняты. Разберитесь пожалуйста с тестами

2020-10-14 22:20 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-10-15 15:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
- should be rendered correctly
- should not have default sorting
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
- should sort "asc" correctly for "sortType" equal number
- should sort "desc" correctly for "sortType" equal number
- should have ability to be destroyed
```
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
NotificationMessage компонент
- should be rendered correctly
- should have ability to set duration
- should be removed after time defined in duration property
- should have ability to set message
- should have ability to set 'success' type of message
- should have ability to set 'error' type of message
- should have ability to define target element for rendering
- should have ability to be destroyed
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-10-16 08:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
- should be rendered correctly
- should not have default sorting
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
- should sort "asc" correctly for "sortType" equal number
- should sort "desc" correctly for "sortType" equal number
- should have ability to be destroyed
```
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-10-16 17:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should have ability to be destroyed
- should not have default sorting
- should sort "asc" correctly for "sortType" equal string
- should sort "desc" correctly for "sortType" equal string
- should sort "asc" correctly for "sortType" equal number
- should sort "desc" correctly for "sortType" equal number
```
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

2020-10-16 21:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-18 16:48 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +static ActiveNote;
с заглавного символа именуются только классы и функции конструкторы. Статические свойства - Нет

2020-10-18 16:48 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  this.durSec = duration / 1000 + "s";
good 👍

2020-10-18 16:48 UTC, dosandk approved these changes
good 👍 
поправьте пожалуйста тесты

2020-10-18 16:50 UTC, merged